image: debian/buster

environment:
  # Ugly hack to prepend to PATH:
  #   ~/.local/bin - for pipx installed `poetry`
  PATH: /home/build/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/games

packages:
  - python3-all-dev
  - python3-pip
  - libpq-dev # for psycopg2
  - pipx
  - python3-venv # for pipx

tasks:

  - setup: |
      cd caophim
      pipx install poetry
      python3 -m venv ~/venv
      source ~/venv/bin/activate
      poetry install

  - test: |
      cd caophim
      source ~/venv/bin/activate
      manage test # `manage` is a script installed with the caophim package
