db:
  image: postgres:11
  environment:
    POSTGRES_USER: caophim
    POSTGRES_PASSWORD: password
    POSTGRES_DB: caophim
  ports:
    - 127.0.0.1:5432:5432
  volumes:
    - ../pgdata:/var/lib/postgresql/data
